version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: bitlink-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - backend
    restart: unless-stopped


  backend:
    image: ghcr.io/yhqz1/bitlink-backend:prod
    env_file:
      - ./backend.env
    expose:
      - "3000"
      - "9100"
    restart: unless-stopped

  queue-worker:
    image: ghcr.io/yhqz1/bitlink-backend:prod
    env_file:
      - ./backend.env
    command: ["node", "workers/analytics.worker.js"]
    expose:
      - "9101"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: bitlink-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: bitlink-grafana
    ports:
      - "3001:3000"
    restart: unless-stopped
