global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "bitlink-backend"
    static_configs:
      - targets: ["backend:9100"]

  - job_name: "bitlink-worker"
    static_configs:
      - targets: ["queue-worker:9101"]
