name: Deploy Backend to EC2

on:
  workflow_run:
    workflows: ["Build Backend Image"]
    types:
      - completed

jobs:
  deploy-backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set lowercase repo owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Deploy backend on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: OWNER_LC
          script: |
            set -e

            echo "→ Moving to project directory"
            cd /home/ubuntu/bitLink

            echo "→ Logging into GHCR"
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_TOKEN }}

            echo "→ Pulling backend image"
            docker pull ghcr.io/$OWNER_LC/bitlink-backend:${{ github.event.workflow_run.head_sha }}

            echo "→ Updating docker-compose image"
            sed -i "s|image: .*bitlink-backend:.*|image: ghcr.io/$OWNER_LC/bitlink-backend:${{ github.event.workflow_run.head_sha }}|" docker-compose.yaml

            echo "→ Restarting backend container"
            docker compose up -d backend

            echo "Backend deployed successfully"
      - name: Trigger Vercel frontend deploy
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
